name: Still Amazing!
on: 
  repository_dispatch:
    types: [still-amazing]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Append to file
        run: go run ./main.go
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Add entry'
          file_pattern: 'amazing.txt'
